version: "3.4"

services:
  fluffbot:
    image: lafayette.api:0.1.3
    build:
      context: .
      dockerfile: ./backend.dockerfile
    env_file:
      - backend.env
    environment:
      NODE_ENV: production
    ports:
      - 9238:9238
