export { default as HanekeIcon } from "./haneke.png"
export { default as Lafayette } from "./lafayette.png"
export { default as LoadAnimation } from "./load.gif"
export { default as ShortcutIcon } from "./shortcut.svg"
export { default as SlackIcon } from "./slack.svg"
export { default as PuppyError } from "./error.gif"
export { default as PuppyWag } from "./wag.gif"
export { default as PuppySleep } from "./sleep.gif"
import Send from "./send.svg"
